WEBHOOK = "YOUR_WEBHOOK_HERE"
BACKUP_WEBHOOK = "" # Optional
INJECTION = True
OBFUSCATION = True    
JUNK_CODE = True       
UPX = False            
FAKE_ERROR = False      
ERROR_TITLE = "System Error"
ERROR_MESSAGE = "The application failed to start (0xc000007b)."
USE_ICON = False        
ICON_PATH = "ignium.ico" 
STARTUP = True
